name: CI  

on:  
  push:  
    branches: [main]  
  pull_request:  
    branches: [main]  

jobs:  
  test:  
    runs-on: ubuntu-latest  

    strategy:
      matrix:
        node-version: [18, 22]

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3

      - name: Setup Node.js  
        uses: actions/setup-node@v2 
        with:  
          node-version: '22' 

      - name: Install dependencies  
        run: npm install  

      - name: Run tests  
        run: npm test  
